(function () {
  const IDEA_COUNT = 50;
  const seeds = {
    "共感": ["平気なふりしてる人ほど分かる気がする。","みんな本当はちょっと疲れてない？","言わないだけで、抱えてる人多そう。","ちゃんとしたいのに、そこで止まる日がある。","自分だけじゃないと思いたい。","一日が少し重くなる。","笑えるけど、少しだけ本気でつらい。","地味に消耗する。","気にしない人になりたかった。","小さいことなのに心に残る。","ちゃんと話すと長くなる人いる？","余裕がない日は、それすら刺さる。","生活の端っこにある本音かも。","黙っちゃう瞬間、あるよね。","強く言えないけど、けっこう分かる。","なんでもない顔で残り続ける。","ちょっと安心した人いる？","疲れてる時ほど響く。","これだけで今日の説明になる。","分かる人だけでいい。","笑える日は、たぶんまだ大丈夫。"],
    "違和感": ["普通っぽいのに少しだけ変。","なんか引っかかったの自分だけ？","説明できないズレだけ残った。","正しそうで少し怖い。","みんな流してるけど、変じゃない？","言葉にしにくいノイズがある。","気づいた瞬間、戻れなくなる。","慣れたら終わりな気がしてる。","便利なのに妙にざらつく。","小さい違和感の入口。","笑って済ませていいのかな。","当たり前になる空気、少しこわい。","嫌いじゃないのに落ち着かない。","なぜか心が一歩引く。","きれいに見えるほど違和感が残る。","まだ名前のないズレがある。","見て黙った人、たぶん同じ。","正解っぽい顔をした未解決。","気にしない人には見えない線。","どこから普通じゃなくなった？","言語化すると少し空気が変わる。"],
    "懐かしさ": ["昔どこかで見た気がする。","懐かしいのに少しだけ寂しい。","急に昔を思い出す人いる？","夕方の匂いがある。","戻れない場所みたいで残る。","懐かしい理由、うまく言えない。","古い記憶が少し起きる。","忘れてた温度だけ戻ってきた。","なぜか平成の端っこ感ある。","誰かの実家みたいな安心感がある。","懐かしさと不安の間にある。","胸が少し痛いの、何なんだろう。","もう戻れない日の光がある。","古いけど、終わってない感じがする。","見て静かになる人、いると思う。","記憶のすみに残ってた景色みたい。","懐かしいものほど少し怖い。","誰の記憶にも少しありそう。","見た瞬間、昔の音がした。","説明より先に懐かしい。","思い出す場所、ある？"],
    "深夜テンション": ["深夜だから言うけど、妙に刺さる。","午前2時に考えるの危険。","朝見たら消したくなる本音。","眠れない夜ほど大きく見える。","深夜だけ正体を出さない？","今だけ言う。かなり分かる。","冷静じゃないけど、嘘でもない。","考えてたら眠れなくなった。","午前2時の脳にちょうどいい。","深夜の判断なので許してほしい。","夜だけ少し意味が変わる。","静かな時間に見ると少し危ない。","昼なら流せるのに、夜は残る。","急に人生を考え始める夜ある。","眠れないので違和感だけ置いておく。","深夜にだけ本音っぽくなる。","気になる夜、だいたい疲れてる。","変に優しくて怖い。","寝たら忘れるかもしれないけど。","今だけ分かる人いる？","午前2時だけ妙に正しい気がする。"],
    "地方感": ["地方だと妙にリアル。","都会の言葉だと説明しにくい。","派手じゃないけど、ちゃんと濃い。","ローカルな生活感がある。","地元を思い出す人いる？","地方の静かな強さがある。","説明しない方が伝わる空気。","この距離感が地方っぽい。","店の裏口みたいなリアルがある。","きれいすぎないから残る。","なんか実家感あると思った。","地方の夕方みたいな温度。","小さい町の大きい感情。","地元の人ほど黙るかも。","地方でしか出ない間がある。","不便さごと愛着になる感じ。","都会なら見逃されそう。","静けさが地方のリアルに近い。","何も起きてないのに見てしまう。","安心するの、地方出身だから？","地味だけど嘘がない。"],
    "ちょい怖": ["よく考えると少し怖い。","背中が少し静かになった。","怖いほどじゃないのに残る。","日常の端にある不穏。","気づかない方がよかったかも。","考えすぎならいいんだけど。","普通さが逆にちょっと怖い。","安心できないの、なぜ。","説明できない怖さだけある。","明るい場所で見るほど不穏。","どこかで見た怖さじゃない？","怖い話の前半みたい。","違和感があとから来る。","誰も気にしてないのが怖い。","静かすぎるものは少し怖い。","日常に混ざってるから怖い。","見たあと少し黙った。","怖くない顔をした怖さ。","余白に何かある気がする。","これ以上考えない方がいい？","何も起きてないのが怖い。"]
  };
  const hookByCategory = { "共感":"共感", "違和感":"違和感", "懐かしさ":"懐かしさ", "深夜テンション":"深夜", "地方感":"地方", "ちょい怖":"薄い不穏" };
  const tuneMap = { "共感":["共感","深夜テンション"], "違和感":["違和感","ちょい怖"], "懐かしさ":["懐かしさ","地方感"] };
  function normalizeTheme(theme) { return theme.trim().replace(/\s+/g, " ") || "まだ名前のない違和感"; }
  function shuffle(items) { const copy = [...items]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
  function scoreIdea(text, category, hook, index) { const lengthScore = text.length >= 20 && text.length <= 90 ? 18 : 5; const categoryScore = category === "違和感" || category === "ちょい怖" ? 10 : 7; const hookScore = hook.includes("共感") || hook.includes("違和感") ? 8 : 5; const rhythm = index % 9 === 0 ? 5 : Math.floor(Math.random() * 9); return Math.max(48, Math.min(98, 54 + lengthScore + categoryScore + hookScore + rhythm)); }
  function polishLength(text, theme) { const clean = text.replace(/\s+\n/g, "\n").replace(/\n{3,}/g, "\n\n").trim(); if (clean.length <= 90) return clean; const compactTheme = theme.length > 22 ? `${theme.slice(0, 22)}…` : theme; return clean.replaceAll(theme, compactTheme).slice(0, 88).replace(/[、。,.!?？!]*$/, "") + "。"; }
  function normalizeIdea(idea, fallbackCategory = "違和感", index = 0) { const text = polishLength(String(idea.text || "").trim(), ""); const category = idea.category || fallbackCategory; const hook = idea.hook || idea.hookType || hookByCategory[category] || "余白"; return { id: `${Date.now()}-${index}-${Math.random().toString(36).slice(2, 8)}`, text, category, score: Number(idea.score) || scoreIdea(text, category, hook, index), hookType: hook, status: "new", createdAt: new Date().toISOString() }; }
  function generate({ theme, category, count = IDEA_COUNT, tune = null }) { const cleanTheme = normalizeTheme(theme); const cats = tuneMap[tune] || [category]; const buckets = cats.map((cat) => ({ cat, rows: shuffle(seeds[cat] || seeds["違和感"]), cursor: 0 })); let lastText = ""; let lastCat = ""; return Array.from({ length: count }, (_, index) => { const bucket = buckets[index % buckets.length]; let seed = bucket.rows[bucket.cursor % bucket.rows.length]; bucket.cursor += 1; if ((seed === lastText || bucket.cat === lastCat) && bucket.rows.length > 1) { seed = bucket.rows[bucket.cursor % bucket.rows.length]; bucket.cursor += 1; } lastText = seed; lastCat = bucket.cat; const text = polishLength(`${cleanTheme}、${seed}`, cleanTheme); const hook = hookByCategory[bucket.cat] || "余白"; return normalizeIdea({ text, category: bucket.cat, score: scoreIdea(text, bucket.cat, hook, index), hook }, bucket.cat, index); }); }
  window.TemplateGenerator = { IDEA_COUNT, generate, normalizeIdea, normalizeTheme };
})();
