const KEY='yume_app_state_v9';
const cfg={name:'ここから',subtitle:'止まっていたものを、少しだけ動かすノート',...(window.YUME_APP_CONFIG||{})};
const $=q=>document.querySelector(q);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const cut=(v,n=54)=>{v=String(v||'').trim();return v.length>n?v.slice(0,n)+'...':v};
let state={screen:'top',plan:null,result:null,step:0};
try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.plan&&s?.result)state={...state,...s,screen:'result'}}catch(e){}
const steps=['入力を読んでいます','Web上の情報を見ています','似た人の流れを探しています','今日できそうな形にしています'];
function render(){style();$('#app').innerHTML=view[state.screen]();bind()}
const view={
 top:()=>`<section class="page home"><div class="shell"><header class="nav"><div class="brand">${esc(cfg.name)}</div><button class="ghost-button" data-go="form">少し整理する</button></header><section class="hero-soft"><p class="eyebrow">${esc(cfg.subtitle)}</p><h1>止まっていたものを、<br>少しだけ動かす。</h1><p class="lead">TavilyでWeb上の事例を見て、今日できる一歩に分けます。</p><button class="primary-button" data-go="form">市場を見て整理する</button></section></div></section>`,
 form:()=>`<section class="page"><div class="shell narrow"><button class="ghost-button" data-go="top">戻る</button><div class="intro"><p class="eyebrow">まずは、軽く聞かせてください</p><h2>いつかやりたいまま止まってること、ありますか？</h2></div><form class="soft-card form-card" id="f"><div class="form-grid">${inp('dreamTitle','いつかやってみたいこと','地方でCNC加工の小さな工場を持ちたい')}${inp('currentAge','今の年齢','44','number')}${inp('targetAge','何歳くらいまでに形にしたいか','50','number')}${inp('availableTime','使えそうな時間','平日30分、週末2時間')}${inp('availableMoney','使えそうなお金','月1万円くらい')}${inp('skills','これまでの経験','CNC経験14年、過去作品あり')}</div>${ta('targetDescription','どんな形になったら少しうれしいですか？','小さな受注、SNS発信、工場を持つ準備など')}${ta('currentSituation','今の状況','子供4人。会社員で平日は忙しい。')}${ta('anxieties','気になっていること','今さら感とお金の不安')}<p class="error" id="err"></p><div class="form-footer"><p>WorkerでWeb調査してから整理します。</p><button class="primary-button">調べて整理する</button></div></form></div></section>`,
 loading:()=>`<section class="page center-page"><div class="shell narrow"><div class="soft-card breathing"><p class="eyebrow">調べています</p><h2>${esc(steps[state.step])}</h2><p class="lead small">市場情報、似た事例、落とし穴を見ています。</p><div class="agent-list">${steps.map((s,i)=>`<div class="agent ${i===state.step?'active':i<state.step?'done':''}"><span></span><div><strong>${['入力','市場','事例','一歩'][i]}</strong><p>${esc(s)}</p></div></div>`).join('')}</div></div></div></section>`,
 result:()=>{const r=norm(state.result,state.plan),a=r.todayActions[0];return `<section class="page"><div class="shell stack"><header class="result-header"><div><p class="eyebrow">Web調査から整理しました</p><h2>まずこれだけ。</h2></div><div class="actions compact"><button class="ghost-button" data-go="form">入力を直す</button><button class="ghost-button" id="reset">記録を消す</button></div></header><section class="conclusion-panel"><p class="eyebrow">まず結論</p><h2>${esc(r.conclusion.title)}</h2><p>${esc(r.conclusion.body)}</p><div class="tag-row">${r.conclusion.tags.map(x=>`<span>${esc(x)}</span>`).join('')}</div></section><section class="today-panel"><p class="eyebrow">今日の一歩</p><h2>${esc(a.title)}</h2><p class="panel-note">${esc(a.description)}</p>${meter(a.estimatedMinutes)}<div class="today-list">${r.todayActions.map(cardAction).join('')}</div></section><section class="soft-card"><details open class="why"><summary>なぜそう見えた？</summary><div class="why-grid">${r.reasoningLinks.map(linkCard).join('')}</div></details></section><section class="soft-card"><p class="eyebrow">今の重さ</p><div class="score-grid">${scoreCards(r.scores).join('')}</div></section><section class="soft-card"><p class="eyebrow">市場では</p><div class="market-list">${r.researchNotes.slice(0,3).map(researchCard).join('')}</div></section><section class="soft-card"><p class="eyebrow">似た人の流れ</p><div class="timeline">${timeline(r.similarPatterns[0]).join('')}</div></section><section class="soft-card"><p class="eyebrow">よくある落とし穴</p><div class="mistake-grid">${r.commonMistakes.map(mistakeCard).join('')}</div></section><section class="insight-panel"><p class="eyebrow">今止まってる理由</p><h3>${esc(r.emotionalInsight.plainSummary)}</h3><p class="panel-note">${esc(r.emotionalInsight.detectedConflict)}</p></section><section class="soft-card"><p class="eyebrow">小さな次の流れ</p><div class="phase-cards">${r.phaseTimeline.map(phaseCard).join('')}</div></section></div></section>`}
};
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.go;render()});$('#reset')&&( $('#reset').onclick=()=>{localStorage.removeItem(KEY);state={screen:'top',plan:null,result:null,step:0};render()});$('#f')&&($('#f').onsubmit=submit)}
async function submit(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget).entries());p.currentAge=+p.currentAge;p.targetAge=+p.targetAge;if(!p.dreamTitle||!p.currentAge||!p.targetAge||!p.currentSituation){$('#err').textContent='気になっていること、年齢、今の状況だけ入れてください。';$('#err').style.display='block';return}state={screen:'loading',plan:p,result:null,step:0};render();const t=setInterval(()=>{state.step=Math.min(state.step+1,3);render()},1200);state.result=await analyze(p);clearInterval(t);state.screen='result';localStorage.setItem(KEY,JSON.stringify({plan:p,result:state.result}));render();scrollTo({top:0,behavior:'smooth'})}
async function analyze(plan){const endpoint=window.YUME_AI_ENDPOINT;if(!endpoint)return fallback(plan);const body={plan,researchContext:{provider:'worker',generatedQueries:queries(plan),notes:[]}};try{const c=new AbortController();setTimeout(()=>c.abort(),90000);const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal});if(!res.ok)return fallback(plan);return await res.json()}catch(e){return fallback(plan)}}
function queries(p){const text=[p.dreamTitle,p.currentSituation,p.skills,p.anxieties].join(' '),age=p.currentAge>=50?'50代':p.currentAge>=40?'40代':'中高年',cat=/CNC|加工|製造|工場|工房|ものづくり|作品/.test(text)?'ものづくり':'副業';return[`${age} 副業 ${cat} 始め方 実例`,/地方|地域|地元/.test(text)?`地方 起業 ${cat} 小さく始める 事例`:`${cat} 個人事業 小さく始める 事例`,/子供|家族|育児|介護/.test(text)?`家族あり 副業 ${cat} 始め方`:`中高年 再挑戦 ${cat} 始め方`,/CNC|加工|製造|工場|工房|作品/.test(text)?'CNC 個人事業 SNS 集客 小受注':`${cat} SNS 発信 個人販売`]}
function norm(v,p){const f=fallback(p);v=v&&typeof v==='object'?v:{};const actions=arr(v.todayActions,f.todayActions).slice(0,3).map((x,i)=>({title:s(x.title||x.action,f.todayActions[i]?.title),description:s(x.description,f.todayActions[i]?.description),estimatedMinutes:+(x.estimatedMinutes||f.todayActions[i]?.estimatedMinutes||10),whyThisAction:s(x.whyThisAction||x.actionReason||x.reason,f.todayActions[i]?.whyThisAction),researchBasis:s(x.researchBasis||x.basis,f.todayActions[i]?.researchBasis)}));return{conclusion:{title:s(v.conclusion?.title,f.conclusion.title),body:s(v.conclusion?.body,f.conclusion.body),tags:arr(v.conclusion?.tags,f.conclusion.tags).slice(0,4)},todayActions:actions,researchNotes:arr(v.researchNotes,f.researchNotes),reasoningLinks:arr(v.reasoningLinks,f.reasoningLinks),scores:v.scores||f.scores,similarPatterns:arr(v.similarPatterns,f.similarPatterns),commonMistakes:arr(v.commonMistakes,f.commonMistakes),phaseTimeline:arr(v.phaseTimeline,f.phaseTimeline).slice(0,4),detectedBlocks:arr(v.detectedBlocks,f.detectedBlocks),emotionalInsight:{plainSummary:s(v.emotionalInsight?.plainSummary||v.emotionalInsight?.summary,f.emotionalInsight.plainSummary),detectedConflict:s(v.emotionalInsight?.detectedConflict,f.emotionalInsight.detectedConflict)}}}
function fallback(p){const a={title:'作れるものを5個だけ書く',description:'売れるかは考えず、手元の経験だけを書きます。',estimatedMinutes:8,whyThisAction:'頭の中だけに置くより、次の一歩が見えやすいからです。',researchBasis:'Workerに接続できないため、ローカル整理です。'};return{conclusion:{title:'今あるものから、小さく外へ出すのがよさそうです。',body:'大きく決める前に、手元の経験を見える形にします。',tags:['ローカル整理','8分','無理しない']},todayActions:[a],researchNotes:[{title:'Worker未接続',finding:'市場調査にはCloudflare Worker接続が必要です。',sourceType:'risk',whyItMatters:'本番ではTavily検索結果がここに出ます。',confidence:'low',url:''}],reasoningLinks:[{fact:`経験: ${cut(p.skills)}`,research:'手元の経験を外に出す方が軽いです。',therefore:a.title}],scores:{financialPressure:70,executionPower:55,socialResistance:68,burnoutRisk:62,stabilityNeed:76},similarPatterns:[{label:'似た流れ',summary:'今あるものを出す → 近い人に見せる → 少し直す',timeline:['今あるものを出す','近い人に見せる','少し直す']}],commonMistakes:[{label:'大きく始めすぎる',whyCommon:'形から入ると重くなります。',softAvoidance:'今日できそうな一歩へ戻します。'}],phaseTimeline:[{title:'今あるものを出す',goal:'手元の経験を見える形にする。',smallAction:a.title,whyNow:'新しく作るより軽いからです。',researchBasis:'ローカル整理です。'}],detectedBlocks:[{title:'お金の不安',plainDescription:`「${cut(p.availableMoney)}」が気になっています。`,softCounterAction:'0円でできる一歩へ戻す。'}],emotionalInsight:{plainSummary:'動きたい気持ちと、怖さが同時にあります。',detectedConflict:`「${cut(p.anxieties)}」が重さになっていそうです。`}}}
function s(v,f){return typeof v==='string'&&v.trim()?v:f}function arr(v,f){return Array.isArray(v)&&v.length?v:f}
function inp(n,l,p,t='text'){return`<label><span>${esc(l)}</span><input name="${n}" type="${t}" placeholder="${esc(p)}"></label>`}function ta(n,l,p){return`<label><span>${esc(l)}</span><textarea name="${n}" placeholder="${esc(p)}"></textarea></label>`}
function meter(m){m=Math.max(5,Math.min(15,+m||10));let lv=m<=7?1:m<=11?2:3;return`<div class="load-meter"><p>行動負荷</p><div class="load-bars">${[1,2,3].map(i=>`<span class="${i<=lv?'on':''}"></span>`).join('')}</div><strong>${m}分</strong></div>`}
function cardAction(x){return`<article class="today-card"><div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><p class="reason-line"><strong>なぜ今これ？</strong>${esc(x.whyThisAction)}</p><small>${esc(x.researchBasis)}</small></div><span>${x.estimatedMinutes}分</span></article>`}
function linkCard(x){return`<article class="reason-card"><span>入力</span><p>${esc(x.fact)}</p><span>市場</span><p>${esc(x.research)}</p><strong>${esc(x.therefore)}</strong></article>`}
function researchCard(x){let url=x.url?`<a href="${esc(x.url)}" target="_blank" rel="noreferrer">参照元を見る</a>`:'';return`<article class="research-card"><div><span>${esc(({market:'市場',case:'似た人',risk:'注意',trend:'流れ'})[x.sourceType]||'メモ')}</span><small>${esc(({high:'高',medium:'中',low:'低'})[x.confidence]||'中')}</small></div><strong>${esc(x.title||x.topic)}</strong><p>${esc(x.finding)}</p><small>${esc(x.whyItMatters)}</small>${url}</article>`}
function scoreCards(sc={}){return[['お金の重さ',sc.financialPressure],['人に見せる重さ',sc.socialResistance],['疲れやすさ',sc.burnoutRisk],['生活を守りたい気持ち',sc.stabilityNeed]].map(([l,v])=>{v=Math.max(0,Math.min(100,+v||0));return`<article class="score-card"><div><strong>${l}</strong><span>${v}</span></div><div class="score-bar"><i style="width:${v}%"></i></div></article>`})}
function timeline(x){x=x||{label:'似た流れ',summary:'',timeline:['今あるものを出す','近い人に見せる','少し直す']};return[`<article class="similar-head"><strong>${esc(x.label)}</strong><p>${esc(x.summary||x.evidence||'')}</p></article>`,...(x.timeline||[]).slice(0,4).map((t,i)=>`<article class="similar-step"><span>${i+1}</span><p>${esc(t)}</p></article>`)]}
function mistakeCard(x){return`<article class="mistake-card"><strong>${esc(x.label||x.title)}</strong><p>${esc(x.whyCommon||x.description)}</p><small>${esc(x.softAvoidance||x.avoidance)}</small></article>`}function blockCard(x){return`<article class="emotion-chip"><strong>${esc(x.title)}</strong><p>${esc(x.plainDescription||x.description)}</p><small>${esc(x.softCounterAction||'今日できそうな形に小さくします。')}</small></article>`}function phaseCard(x){return`<article class="phase-card"><h3>${esc(x.title||x.phase)}</h3><p>${esc(x.goal)}</p><strong>${esc(x.smallAction)}</strong><div class="phase-reasons"><article><span>なぜ今</span><p>${esc(x.whyNow||x.reason)}</p></article><article><span>市場</span><p>${esc(x.researchBasis)}</p></article></div></article>`}
function style(){if($('#v5-style'))return;let st=document.createElement('style');st.id='v5-style';st.textContent=`.conclusion-panel{border:1px solid rgba(139,187,194,.38);border-radius:26px;background:linear-gradient(135deg,rgba(255,253,247,.92),rgba(220,238,241,.56));padding:24px;box-shadow:0 18px 60px rgba(96,111,99,.08)}.conclusion-panel h2{font-size:clamp(28px,5vw,44px);letter-spacing:0}.tag-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.tag-row span{border:1px solid rgba(139,187,194,.36);border-radius:999px;background:rgba(255,253,247,.78);padding:8px 12px;color:#527a80;font-weight:900}.why-grid,.phase-reasons,.market-list,.phase-cards,.mistake-grid,.score-grid{display:grid;gap:12px;margin-top:16px}.reason-card,.research-card,.phase-card,.score-card,.mistake-card,.similar-head,.similar-step{border:1px solid rgba(231,222,207,.9);border-radius:18px;background:rgba(255,253,247,.72);padding:14px}.reason-card span,.research-card span,.phase-reasons span{color:#527a80;font-size:12px;font-weight:900}.research-card>div,.score-card>div:first-child{display:flex;justify-content:space-between;gap:10px}.research-card a{display:inline-block;margin-top:8px;color:#66865e;font-weight:900}.score-bar{height:9px;border-radius:999px;background:rgba(231,222,207,.8);overflow:hidden;margin-top:10px}.score-bar i{display:block;height:100%;background:linear-gradient(90deg,#8bbd92,#95cfd8)}.load-meter{display:flex;align-items:center;gap:12px;width:fit-content;margin-top:18px;border:1px solid rgba(139,187,194,.42);border-radius:999px;background:rgba(255,253,247,.78);padding:9px 12px}.load-bars{display:flex;gap:5px}.load-bars span{width:22px;height:8px;border-radius:999px;background:rgba(231,222,207,.9)}.load-bars .on{background:var(--leaf-strong)}.similar-timeline{display:grid;gap:10px;margin-top:16px}.similar-step{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:10px}.similar-step span{width:28px;height:28px;display:grid;place-items:center;border-radius:999px;background:var(--sky);color:#527a80;font-size:12px;font-weight:900}.phase-card>strong,.reason-card strong{display:block;margin-top:10px;border-radius:14px;background:rgba(223,234,217,.62);color:#66865e;padding:10px 12px}@media(min-width:760px){.why-grid,.phase-reasons,.mistake-grid,.score-grid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(st)}
loadState();render();
